### ISSUE TITLE
Usage outside of Foxx

### ISSUE THREAD

**Issue by sarendipitee** [Bonsaya/arangodb-timetravel#1]
Is there anyway to use this outside of foxx? Perhaps exposing some HTTP endpoints that another service/api can use to insert/upsert documents?

**Comment by KevinExtremo** [comment]
Hey JonDum,

There are several ways of achieving this. Let me run you through them and why neither has been implemented yet.

**Implementation 1:**

We convert everything that currently uses Foxx to use the [HTTP version](https://github.com/arangodb/arangojs) from ArangoDB. 

But I was hoping nobody would attempt this, because there is a major downside to this. Due to the nature of the way this framework works, a single repsert may result into multiple inserts/replaces internally. The same goes for the upserts and forth. That would mean that you need to launch multiple HTTP requests and to my knowledge, ArangoDB currently only supports HTTP/1.1 which has significant overhead as you constantly need to go through the handshake and establish a connection. There are no long-lived connections and this would drastically alter the performance.

Not to mention that currently, the framework is incredibly fast simply because it lives in memory with the data(almost) thanks to how tightly coupled Foxx is with the database. Another feature that would thus be lost.

We'd also lose transactions, but this can be a desired outcome since currently, ArangoDB does not allow transactions in an environment with more than a single server. So either way, this framework will eventually (if adopted) need the option to turn transactions off.

**Implementation 2:**

We develop a layer on top of the current framework that acts as a proxy. Everytime you invoke, let's say a REST API endpoint(we're stuck to that, because of the synchronous nature of Foxx, although I'd much prefer a long living connection of some sort, HTTP/2). Each Endpoint could then receive one function call of the framework and trigger the Foxx function. This should at least increase the performance by about 300% thanks to the avoidance of the multiple HTTP requests necessary for a single action of my framework.

You're also going to maintain the benefit of doing everything in memory, however, the nature of HTTP/1.1 still means you need to perform some form of a handshake and establishing a connection and your performance will suffer.

**Conclusion**

It is entirely possible to achieve this. It was in fact always in my mind and on my roadmap. Sadly I must admit that I was hoping for more adoption of this framework. I spend hours upon hours making this and working closely with ArangoDB, in fact, to make this happen. I wrote an incredibly detailed documentation for this framework and I was betting largely on the adoption of this framework so that I am no longer the sole developer.

We lack a lot of resources to continuously develop all our frameworks both internally and publically and I really needed the help. It seems though that the adoption of this framework is almost non-existent and so, neither any issues nor any help was raised and at least currently, I am no longer adding or changing the functionality of this framework anymore.

Of course I would still fix any bugs that arise and take my time to answer questions like yours. Let me know if this answers your question or if you need any more help. I'll be glad to support anyone willing to give this framework a shot :)

**Comment by wtcross** [comment]
@KevinExtremo FWIW I'm going to be using this framework. Thank you for creating it! I'm still learning ArangoDB, but will eventually be able to help out here.
