### ISSUE TITLE
Use suffix instead of appendix

### ISSUE THREAD

**Issue by johnrees** [Bonsaya/arangodb-timetravel#2]
Just a little semantics suggestion, as you mention using prefixes in the docs e.g. `servicePrefix`, it might be more consistent to replace the settings keys with ...Suffix, so `settings.presentAppendix` > `settings.presentSuffix`.

Thanks for sharing the library anyway, it looks very interesting!

**Comment by KevinExtremo** [comment]
Hello John,

Thanks for the suggestion. You're totally right on this one. A good and clear name that carries the information necessary is extremely important.

This change is, however, slightly more complicated as I need to differentiate between the old and new settings object since this word essentially becomes a key to a value pair. I'll take a look later when I have time, but a great suggestion!
